import {
  ACCUMULATION_RADIUS_KM,
  ACCUMULATION_REINSURE_THRESHOLD_EUR,
  CAPACITY_SQM_PER_VEHICLE,
  CLIMATE_LOADING_FACTOR,
  DETECTION_CONFIDENCE,
  FLOOD_DAMAGE_CURVE,
  HAIL_DAMAGE_FRACTION_BASE,
  HEAT_DAMAGE_FRACTION_PER_HOTDAY,
  HEAT_HOTDAYS_SCORE_MAX,
  LIGHTNING_DAMAGE_FRACTION,
  PML_CLUSTER_RADIUS_KM,
  PML_DAMAGE_FRACTION,
  SCENARIO_INTENSITY_DAMAGE,
  SITE_HIT_PROBABILITY,
  SNOW_LOAD_DAMAGE_FRACTION_PER_30CM,
  VEHICLE_VALUE_DEFAULT_EUR,
  VEHICLE_VALUE_EUR,
  WIND_DAMAGE_FRACTION,
  WIND_SITE_HIT_PROBABILITY,
  WIND_STORM_THRESHOLD_KMH,
} from "./constants";
import { RiskParametersSchema, type RiskParameters } from "./types";

/** Defaults used for new portfolios and for old sessions without parameters. */
export const DEFAULT_RISK_PARAMETERS: RiskParameters = {
  vehicleValueCarEur: VEHICLE_VALUE_EUR.car,
  vehicleValueVanEur: VEHICLE_VALUE_EUR.van,
  vehicleValueTruckEur: VEHICLE_VALUE_EUR.truck,
  vehicleValueBusEur: VEHICLE_VALUE_EUR.bus,
  vehicleValueDefaultEur: VEHICLE_VALUE_DEFAULT_EUR,
  capacitySqmPerVehicle: CAPACITY_SQM_PER_VEHICLE,
  hailDamageFraction: HAIL_DAMAGE_FRACTION_BASE,
  hailSiteHitProbability: SITE_HIT_PROBABILITY,
  climateLoadingFactor: CLIMATE_LOADING_FACTOR,
  windStormThresholdKmh: WIND_STORM_THRESHOLD_KMH,
  windDamageFraction: WIND_DAMAGE_FRACTION,
  windSiteHitProbability: WIND_SITE_HIT_PROBABILITY,
  lightningDamageFraction: LIGHTNING_DAMAGE_FRACTION,
  lightningDensityScale: 0.001,
  snowLoadDamageFractionPer30cm: SNOW_LOAD_DAMAGE_FRACTION_PER_30CM,
  floodDamageHq10: FLOOD_DAMAGE_CURVE.HQ10,
  floodDamageHq100: FLOOD_DAMAGE_CURVE.HQ100,
  floodDamageHqExtrem: FLOOD_DAMAGE_CURVE.HQextrem,
  heatHotdaysScoreMax: HEAT_HOTDAYS_SCORE_MAX,
  heatDamageFractionPerHotday: HEAT_DAMAGE_FRACTION_PER_HOTDAY,
  windScoreMaxKmh: 120,
  lightningScoreMaxDensity: 5,
  snowScoreMaxCm: 50,
  floodScoreMaxAnnualPrecipMm: 1200,
  pmlDamageFraction10: PML_DAMAGE_FRACTION[10],
  pmlDamageFraction50: PML_DAMAGE_FRACTION[50],
  pmlDamageFraction100: PML_DAMAGE_FRACTION[100],
  pmlClusterRadiusKm: PML_CLUSTER_RADIUS_KM,
  accumulationRadiusKm: ACCUMULATION_RADIUS_KM,
  accumulationReinsureThresholdEur: ACCUMULATION_REINSURE_THRESHOLD_EUR,
  scenarioDamageLow: SCENARIO_INTENSITY_DAMAGE.LOW,
  scenarioDamageMedium: SCENARIO_INTENSITY_DAMAGE.MEDIUM,
  scenarioDamageHigh: SCENARIO_INTENSITY_DAMAGE.HIGH,
  scenarioDamageExtreme: SCENARIO_INTENSITY_DAMAGE.EXTREME,
  alertExtremeScore: 75,
  alertOvercapacity: 1,
  alertLowBoundaryConfidence: 0.3,
  alertEalPortfolioShare: 0.2,
  boundaryReviewConfidence: 0.7,
  boundaryReviewTop2Margin: 0.1,
  boundaryReviewSourceAgreement: 0.35,
  boundaryNearPointDistanceM: 35,
  syntheticBoundaryRadiusM: 100,
  detectionConfidence: DETECTION_CONFIDENCE,
};

/** Normalizes a partial/legacy session value without mutating the input. */
export function normalizeRiskParameters(
  value?: Partial<RiskParameters> | null,
): RiskParameters {
  return RiskParametersSchema.parse({ ...DEFAULT_RISK_PARAMETERS, ...value });
}
