import {
  ACCUMULATION_RADIUS_KM,
  ACCUMULATION_REINSURE_THRESHOLD_EUR,
  CAPACITY_SQM_PER_VEHICLE,
  DETECTION_CONFIDENCE,
  HAIL_FREQUENCY_BY_ZONE,
  HAIL_SEVERITY_CLASSES,
  HEAT_HOTDAYS_SCORE_MAX,
  PML_CLUSTER_RADIUS_KM,
  PML_DAMAGE_FRACTION,
  SCENARIO_INTENSITY_DAMAGE,
  VEHICLE_VALUE_CAR_EUR,
  VEHICLE_VALUE_DEFAULT_EUR,
} from "./constants";
import { RiskParametersSchema, type RiskParameters } from "./types";

/** Defaults used for new portfolios and for old sessions without parameters. */
export const DEFAULT_RISK_PARAMETERS: RiskParameters = {
  vehicleValueCarEur: VEHICLE_VALUE_CAR_EUR,
  vehicleValueDefaultEur: VEHICLE_VALUE_DEFAULT_EUR,
  capacitySqmPerVehicle: CAPACITY_SQM_PER_VEHICLE,
  hailFrequencyZone1: HAIL_FREQUENCY_BY_ZONE[1],
  hailFrequencyZone2: HAIL_FREQUENCY_BY_ZONE[2],
  hailFrequencyZone3: HAIL_FREQUENCY_BY_ZONE[3],
  hailFrequencyZone4: HAIL_FREQUENCY_BY_ZONE[4],
  hailFrequencyZone5: HAIL_FREQUENCY_BY_ZONE[5],
  hailFrequencyZone6: HAIL_FREQUENCY_BY_ZONE[6],
  hailShareSmall: HAIL_SEVERITY_CLASSES.small.share,
  hailShareMedium: HAIL_SEVERITY_CLASSES.medium.share,
  hailShareLarge: HAIL_SEVERITY_CLASSES.large.share,
  hailSeveritySmallEur: HAIL_SEVERITY_CLASSES.small.lossEur,
  hailSeverityMediumEur: HAIL_SEVERITY_CLASSES.medium.lossEur,
  hailSeverityLargeEur: HAIL_SEVERITY_CLASSES.large.lossEur,
  heatHotdaysScoreMax: HEAT_HOTDAYS_SCORE_MAX,
  windScoreMaxKmh: 120,
  lightningScoreMaxDensity: 5,
  snowScoreMaxCm: 50,
  floodScoreMaxAnnualPrecipMm: 1200,
  pmlDamageFraction10: PML_DAMAGE_FRACTION[10],
  pmlDamageFraction50: PML_DAMAGE_FRACTION[50],
  pmlDamageFraction100: PML_DAMAGE_FRACTION[100],
  pmlClusterRadiusKm: PML_CLUSTER_RADIUS_KM,
  accumulationRadiusKm: ACCUMULATION_RADIUS_KM,
  accumulationReinsureThresholdEur: ACCUMULATION_REINSURE_THRESHOLD_EUR,
  scenarioDamageLow: SCENARIO_INTENSITY_DAMAGE.LOW,
  scenarioDamageMedium: SCENARIO_INTENSITY_DAMAGE.MEDIUM,
  scenarioDamageHigh: SCENARIO_INTENSITY_DAMAGE.HIGH,
  scenarioDamageExtreme: SCENARIO_INTENSITY_DAMAGE.EXTREME,
  alertHailZone: 5,
  alertOvercapacity: 1,
  alertLowBoundaryConfidence: 0.3,
  alertEalPortfolioShare: 0.2,
  boundaryReviewConfidence: 0.7,
  boundaryReviewTop2Margin: 0.1,
  boundaryReviewSourceAgreement: 0.35,
  boundaryNearPointDistanceM: 35,
  syntheticBoundaryRadiusM: 100,
  detectionConfidence: DETECTION_CONFIDENCE,
  boundaryGridResolutionM: 0.5,
  boundaryGridExtentM: 400,
  boundaryGrowHighThreshold: 0.6,
  boundaryGrowLowThreshold: 0.15,
  boundaryMaxAreaSqm: 200_000,
  boundaryParcelSnapOverlap: 0.6,
  boundaryVehicleEvidenceWeight: 1,
  boundaryBarrierSupportReview: 0.35,
  boundaryRegularizeAngleToleranceDeg: 12,
};

/** Normalizes a partial/legacy session value without mutating the input. */
export function normalizeRiskParameters(
  value?: Partial<RiskParameters> | null,
): RiskParameters {
  return RiskParametersSchema.parse({ ...DEFAULT_RISK_PARAMETERS, ...value });
}
